---
apiVersion: v1
baseDomain: test.example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: compact-cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.124.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    hosts:
      - name: master-0
        role: master
        bootMACAddress: 52:54:00:e7:05:72
      - name: master-1
        role: master
        bootMACAddress: 52:54:00:95:fd:f3
      - name: master-2
        role: master
        bootMACAddress: 52:54:00:e8:b9:18
    apiVIP: "192.168.124.125"
    ingressVIP: "192.168.124.126"
pullSecret: '<YOUR_PULL_SECRET>'
sshKey: "<YOUR_SSH_PUB_KEY>"
