---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno-cluster
rendezvousIP: 192.168.124.80 ### The address of the host where the Assisted Service will run
hosts: 
  - hostname: master-0
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:c1:54:95
    rootDeviceHints: 
      deviceName: /dev/vda
    networkConfig: ### Network configuration expressed in NMState format
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: 52:54:00:c1:54:95
          ipv4:
            enabled: true
            address:
              - ip: 192.168.124.80
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.1.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.124.1
            next-hop-interface: enp1s0
            table-id: 254
